# Generated by Django 3.0.5 on 2020-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20201119_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='C:\\\\Users\\\\ishit\\\\Downloads\\\\DJANGO\\\\DJANGO\\\\minor\\\\media\\\\website\\\\images\\\\avtar.png', upload_to='website/images'),
        ),
    ]
